name: CI/CD Pipeline
on:
  push:
    branches:
      - main
      - develop
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: .  
        args: >
          -Dsonar.organization=daedov
          -Dsonar.projectKey=daedov_cicd-kc
          -Dsonar.sources=src/
          -Dsonar.tests=test/
          -Dsonar.eslint.reportPaths=lint.json
          -Dsonar.javascript.lcov.reportPaths=../coverage/lcov.info
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
