name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Build the application
        run: npm run build
      - name: Test and coverage
        run: npm run test:cov
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: GitGuardian scan
        uses: GitGuardian/ggshield/actions/secret@v1.26.0
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
  artifacts:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Build the application
        run: npm run start:prod
      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: nestjs-build
          path: dist/ 

